### ISSUE TITLE
Merge Histories Across the Organization

### ISSUE THREAD

**Issue by moovinzoo** [Smile2Buy/.github#1]
### base
- org 내 각 repo의 작업내역이 갱신된 경우 이를 org의 readme에 반영해서 history로써 관리하고 싶다.

### hurdle
- repo 내 Actions의 workflow 권한은 repo 내부로 갇혀있다.

### solution
- 웹 훅 이벤트(repository_dispatch)를 이용하기로 한다.

### details
- 이벤트는 REST API로 동작하기에 권한 문제에서 자유롭다.
- Hub-repo와 Spoke-repo들 간 이벤트를 약속한다.
  - sending event triggered by: spoke repo의 `README.md` 수정
  - received event triggers: history-hub 액션

```[tasklist]
## Tasks
- [x] #4 
- [x] Smile2Buy/s2b-infra#19
- [x] #11
- [x] #16 
```

**Comment by moovinzoo** [comment]
```[tasklist]
- [ ] #2

**Comment by moovinzoo** [comment]
```[tasklist]
- [ ] https://github.com/Smile2Buy/s2b-infra/issues/15

**Comment by moovinzoo** [comment]
## Tasks
- [ ] Configure History-hub Workflow in <.github> repo
- [ ] Configure History-spoke Workflow in <infra> repo
